### ISSUE TITLE
BdbQuitbdb in dispatch_line

### ISSUE THREAD

**Issue by jaclu** [delving/nave#45]
https://sentry.io/delving-bv/brabantcloud_nave/issues/184125935/

this snipet comes from 
acc.brabantcloud.hubs.delving.org:/var/log/hub3-brabantcloud/celery_main.log
This Is generated when celery_main is started, after some 15-20 seconds

[2016-12-05 16:39:30,783: ERROR/MainProcess] Task projects.brabantcloud.tasks.sync_datasets[3e96fae3-e147-43c5-820f-aa5206caebb0] raised unexpected: BdbQuit()
Traceback (most recent call last):
  File "/opt/hub3/brabantcloud/virtenv/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/hub3/brabantcloud/virtenv/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/fra1-brabantcloud-acc-hub3/hub3/brabantcloud/nave/projects/brabantcloud/tasks.py", line 430, in sync_datasets
    lhs_name, rdf_base_url, rights, language, store)
  File "/mnt/fra1-brabantcloud-acc-hub3/hub3/brabantcloud/nave/projects/brabantcloud/tasks.py", line 390, in process_memorix_dataset
    graph_store.post(named_graph, g)
  File "/mnt/fra1-brabantcloud-acc-hub3/hub3/brabantcloud/nave/projects/brabantcloud/tasks.py", line 390, in process_memorix_dataset
    graph_store.post(named_graph, g)
  File "/usr/lib/python3.4/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.4/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

**Comment by kiivihal** [comment]
There was a breakpoint in the client code that was causing this issue. It was committed by mistake. This has since been remove, therefore this issue can be closed.
